# Generated by Django 2.2 on 2020-04-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('vlan_id', models.IntegerField(null=True)),
                ('subnet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subnet.Subnets')),
            ],
        ),
    ]
