# Generated by Django 2.2 on 2020-04-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ips',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
