# Generated by Django 2.2 on 2020-04-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnets',
            name='network_address',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
